name: Python CI with Pip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest  # Chạy trên hệ điều hành Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Kiểm tra mã nguồn từ GitHub vào runner
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Bạn có thể thay đổi thành phiên bản cần dùng
        
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel  # Cập nhật pip, setuptools và wheel

    - name: Install dependencies from requirements.txt
      run: |
        pip install --upgrade --no-cache-dir -r requirements.txt  # Cài đặt gói từ requirements.txt, bỏ qua cache

    - name: Uninstall urllib3 and requests
      run: |
        pip uninstall -y urllib3 requests  # Gỡ cài đặt urllib3 và requests nếu đã có

    - name: Reinstall urllib3 and requests
      run: |
        pip install urllib3 requests  # Cài lại urllib3 và requests

    - name: Run tests with pytest
      run: |
        pip install pytest  # Cài đặt pytest
        pytest ./tests  # Chạy pytest trên thư mục 'tests' (cập nhật nếu bạn có thư mục khác)
