name: Python CI with Pip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest  # Chạy trên hệ điều hành Ubuntu
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Kiểm tra mã nguồn từ GitHub vào runner
      
    # Thiết lập môi trường Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Bạn có thể thay đổi thành phiên bản cần dùng
        
    # Cập nhật pip và các công cụ liên quan
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel  # Cập nhật pip, setuptools và wheel

    # Cài đặt lại yêu cầu từ file requirements.txt
    - name: Install dependencies from requirements.txt
      run: |
        pip install --upgrade --no-cache-dir -r requirements.txt  # Cài đặt gói từ requirements.txt, bỏ qua cache

    # Gỡ cài đặt các phiên bản cũ của urllib3 và requests, nếu chúng có thể gây lỗi
    - name: Uninstall urllib3 and requests
      run: |
        pip uninstall -y urllib3 requests  # Gỡ cài đặt urllib3 và requests nếu đã có

    # Cài lại các gói urllib3 và requests
    - name: Reinstall urllib3 and requests
      run: |
        pip install urllib3 requests  # Cài lại urllib3 và requests

    # Cài đặt pytest để chạy kiểm tra
    - name: Run tests with pytest
      run: |
        pip install pytest  # Cài đặt pytest
        pytest  # Chạy pytest để kiểm tra mã nguồn
