name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10
        environment-file: environment.yml
        activate-environment: test  # Tên environment (test là tên trong environment.yml)

    - name: Verify Conda environment
      run: conda info --envs  # Liệt kê các environment đã tạo

    - name: Install dependencies
      run: conda env update --file environment.yml --name test

    - name: Lint with flake8
      run: |
        conda install -y flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        conda install -y pytest
        pytest
