name: Python CI with Pip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Hoặc phiên bản Python bạn đang sử dụng

    - name: Uninstall conflicting packages (six, urllib3)
      run: |
        pip uninstall -y six urllib3

    - name: Install dependencies with updated pip
      run: |
        pip install --upgrade pip setuptools
        pip install -r requirements.txt  # Cài các dependencies từ requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest
