name: Python CI with Pip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    # Kiểm tra mã nguồn từ GitHub vào runner
    - name: Checkout code
      uses: actions/checkout@v3

    # Thiết lập môi trường Python 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    # Cập nhật pip, setuptools và wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Cài đặt tất cả các gói yêu cầu từ requirements.txt
    - name: Install dependencies from requirements.txt
      run: |
        pip install --upgrade --no-cache-dir -r requirements.txt

    # Kiểm tra sự tồn tại của thư mục 'tests'
    - name: Check if 'tests' directory exists
      run: |
        if [ ! -d "./tests" ]; then echo "No 'tests' directory found!"; else echo "'tests' directory found."; fi

    # Chạy pytest nếu có thư mục tests
    - name: Run tests with pytest
      run: |
        if [ -d "./tests" ]; then
          echo "Running tests in './tests' directory...";
          pytest ./tests;
        else
          echo "No tests to run.";
        fi
