name: Python CI with Pip

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest  # Chạy trên hệ điều hành Ubuntu
    
    steps:
    # Kiểm tra mã nguồn từ GitHub vào runner
    - name: Checkout code
      uses: actions/checkout@v3

    # Thiết lập môi trường Python 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Bạn có thể thay đổi thành phiên bản cần dùng

    # Cập nhật pip, setuptools và wheel
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Cài đặt tất cả các gói yêu cầu từ requirements.txt
    - name: Install dependencies from requirements.txt
      run: |
        pip install --upgrade --no-cache-dir -r requirements.txt

    # Kiểm tra sự tồn tại của thư mục 'tests' mà không thất bại pipeline
    - name: Check if 'tests' directory exists
      run: |
        if [ ! -d "./tests" ]; then echo "No tests directory found!"; fi

    # Kiểm tra nếu có tệp kiểm tra trong thư mục
    - name: Check if tests are present
      run: |
        if [ ! "$(ls -A ./tests)" ]; then echo "No tests found!" && exit 1; fi

    # Chạy pytest trên thư mục 'tests'
    - name: Run tests with pytest
      run: |
        pytest ./tests  # Chạy pytest trên thư mục 'tests'
